global_max_intensity = 10

[source]
type = "wii"
ip = "192.168.137.140"
debug = true

[[modes]]
name      = "action"
intensity = 1
action    = ["SHIELD", "GRAB"]
do_while  = true

[players.1]
output_mode = "vibrate"

[[players.1.modes]]
name      = "action"
intensity = 1
action    = ["SHIELD", "GRAB"]
do_while  = true

[players.2]
output_mode = "disabled"
