global_max_intensity = 10

[source]
type = "wii"
ip = "192.168.137.140"
debug = true

[mode]
name      = "action"
intensity = 1
action = ["SHIELD", "GRAB"]
do_while = true

[players.1]
output_mode = "vibrate"

[players.2]
output_mode = "disabled"

